"""Value table enums."""

from enum import Enum


class RemType(str, Enum):
    section = "section"
    appendix = "appendix"
    paragraph = "paragraph"
    graphic_file = "graphic_file"
    glossary_item = "glossary_item"
    organization = "organization"
    stakeholder = "stakeholder"
    meeting = "meeting"
    objective = "objective"
    actor = "actor"
    information_requirement = "information_requirement"
    constraint_requirement = "constraint_requirement"
    use_case = "use_case"
    functional_requirement = "functional_requirement"
    non_functional_requirement = "non_functional_requirement"
    object_type = "object_type"
    user_defined_value_type = "user_defined_value_type"
    association_type = "association_type"
    system_operation = "system_operation"
    alternative = "alternative"
    conflict = "conflict"
    defect = "defect"
    change_request = "change_request"
    traceability_matrix = "traceability_matrix"
    attribute = "attribute"
    component = "component"
    role = "role"
    parameter = "parameter"
    invariant_expression = "invariant_expression"
    step = "step"
    trace = "trace"
    c_requirements_specification = "c_requirements_specification"
    d_requirements_specification = "d_requirements_specification"
    defects_specification = "defects_specification"
    change_requests_specification = "change_requests_specification"
